version: "3"
services:
  backend:
    build: ./backend
    tty: true
    expose:
      - "8080"
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend
    tty: true
    command: yarn start
    expose:
      - "3000"
    ports:
      - "3000:3000"
